### ISSUE TITLE
Question: No longer maintained?

### ISSUE THREAD

**Issue by dkotrada** [Kotlin/kotlinx.html#166]
Is kotlinx.html no longer maintained?

**Comment by dector** [comment]
Why?
I guess team is busy on other projects. There are no major bugs anyway.

**Comment by dkotrada** [comment]
We just consider what to use Kotlinx.html or jte.gg ...

**Comment by dector** [comment]
@dkotrada I didn't use jte but usually with template engines you can get more hotreload-like functionality. Might be very useful when you are changing only styles - just disable cache for template engine and reload page.

I'm using `kotlinx.html` mostly when I need to generate html snippets or (in rare cases) predesigned html pages. Lib works great but the need to compile Kotlin code makes `change - run - validate` feedback cycle very slow.

**Comment by MartinX3** [comment]
Yes, this project is dead and security issues won't get fixed.

**Comment by MartinX3** [comment]
@elizarov 
Why does it use a old kotlin version, old dependencies and `buildscript`, instead of plugins and an old way to add dependencies?

The ancient code base tells me, that it's not maintained.

The projects
- https://jte.gg/
- https://docs.korge.org/korte/
are maintained.

The most confusing thing for me is, that a project hosted in the `kotlin` organisation doesn't use the newest `kotlin` version.
`1.4.31` is from `2021-02-25`

**Comment by elizarov** [comment]
Kotlin is backward compatible. On Kotlin/JVM you can use can still use libraries compiled with Kotlin 1.0.

**Comment by dkotrada** [comment]
Thank you. I figured out what to use and when.
