### ISSUE TITLE
Stop relying on jcenter & bintray

### ISSUE THREAD

**Issue by Mahoney** [Kotlin/kotlinx.html#173]
As of yesterday [jcenter & bintray are sunsetting](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/) so most of the instructions here:
https://github.com/kotlin/kotlinx.html/wiki/Getting-started
will not work from 1st May 2021.

It would be good to have `org.jetbrains.kotlinx:kotlinx-html-jvm:0.7.2` in maven central.

**Comment by hennr** [comment]
see #81 as well

**Comment by ber4444** [comment]
Is it done already?

https://mvnrepository.com/artifact/org.jetbrains.kotlinx/kotlinx-html-jvm?repo=kotlinx seems to have it

**Comment by Mahoney** [comment]
No - that site is not maven central.

This is: https://repo.maven.apache.org/maven2/org/jetbrains/kotlinx/
As is this: https://search.maven.org/search?q=kotlinx-html-jvm

**Comment by mohsenoid** [comment]
Looking forward to it. ⏳

**Comment by Kobe** [comment]
update: I've asked one of the Jetbrain'ers and they are on it, see https://twitter.com/Kobe/status/1362302455728504832

**Comment by jponge** [comment]
I have a build that fails due to: `org.jetbrains.kotlinx:kotlinx-html-jvm:jar:0.7.2`

**Comment by jponge** [comment]
Any ETA on when the artefacts will be available from Maven Central?

**Comment by maxdelia** [comment]
Any update, please?

**Comment by lordcodes** [comment]
You just need to enable jcenter for this dependency until it is on Maven Central. JCenter will continue serving it until early 2022.

```
jcenter {
    content {
        includeModule("org.jetbrains.kotlinx", "kotlinx-html-jvm")
    }
}
```

Then, you are free to stop using jcenter for all other dependencies until someone who maintains this repo has a chance to look into it.

**Comment by maxdelia** [comment]
@lordcodes Your fix works, thank You!!!

**Comment by hfhbd** [comment]
Alternative use Jetbrains Space:
```kotlin
repositories {
    maven(url = "https://maven.pkg.jetbrains.space/public/p/kotlinx-html/maven")
}

dependencies {
    implementation("org.jetbrains.kotlinx:kotlinx-html-js:0.7.3")
}
```

**Comment by yamin8000** [comment]
This is ridiculous, shame on the people who are responsible!
I tested all the methods provided here so far and nothing helps, I'm still blocked from using dokka because of this:
`org.jetbrains.kotlinx:kotlinx-html-jvm:jar:0.7.2`
is it possible to just add this library as jar?

**Comment by nschulzke** [comment]
@yamin8000, yes, just download it and stick it in your classpath. Alternatively, JCenter will continue serving JAR files until February 1st, so you can just continue using JCenter for now.

While you're at it, please remember that "the people who are responsible" are providing you with free source code to use in your projects. Be respectful of that, and don't demand that their free work be done on *your* timetable.

**Comment by e5l** [comment]
0.7.2 is published in Space as well

**Comment by svilen-ivanov** [comment]
@e5l please confirm that `https://maven.pkg.jetbrains.space/public/p/kotlinx-html/maven` is maintained by JetBrains. I have concerns that someone may create Space account `public` and publish tainted/trojanized packages.

**Comment by jschneider** [comment]
Changing one deprecated repository with another "unusual" repository is not the way.

**Comment by dsvensson** [comment]
Fully signed artifacts take care of that part, and maven central requires signing iirc.

**Comment by ibauersachs** [comment]
@e5l Space? What is that? Yes, yes, that fancy new JetBrains stuff. We don't care. Put it on Maven Central, please. How hard can it be?

**Comment by hfhbd** [comment]
Please follow the code of conduct and the general contribution guide, including language. `kotlinx-html` is a free library, maintained by JetBrains, but licensed under Apache 2 and can be easy mirrored or forked, if wanted.

**Comment by robpridham-bbc** [comment]
> Please follow the code of conduct and the general contribution guide, including language. `kotlinx-html` is a free library, maintained by JetBrains, but licensed under Apache 2 and can be easy mirrored or forked, if wanted.

Whilst I agree about language and behaviour, forking is not a technical solution; mirroring perhaps but it's not normal. Most people who have discovered this issue are not direct users of this library and do not reference it at all - they use other artefacts that incorporate it. We as consumers are responsible for defining repositories but that's it.

For the many faults of JCenter, we at least understood roughly what we could expect from it - it was a service provided to the community. We don't really have any idea of the status of the Space repo suggested as a solution upthread. That might be an interim solution but it would be valuable and best practice to put it in Maven Central.

That said, I'm not clear as to who amongst the respondents is actually a Jetbrains employee and what the status of this issue is - it may still be due to happen.

**Comment by e5l** [comment]
We're working on republishing old artifacts to central. There are several central requirements broken and it takes time to make all stuff right. We made the Space publication because it was the fastest way to provide artifacts, while we working on porting everything to central. Sorry for the delay and confusion.

**Comment by e5l** [comment]
kotlinx.html 0.7.3 is available in mavenCentral
