### ISSUE TITLE
Cannot add a namespace to html tag

### ISSUE THREAD

**Issue by isitinschi** [Kotlin/kotlinx.html#84]
When I am trying to add a namespace to an html tag I have an exception "java.lang.IllegalArgumentException: Tag html has invalid attribute name xmlns"

```
createHTML().html {
      attributes["xmlns"] = "http://www.w3.org/1999/xhtml"
      ...
}
```

According to [w3c](https://www.w3schools.com/tags/att_html_xmlns.asp) it is an absolutely valid scenario.

Also it is impossible to set a _namespace_ like this:
```
createHTML().html {
      namespace = "http://www.w3.org/1999/xhtml"
      ...
}
```
because _namespace_ is a **val** and cannot be reassigned.

Exception happens in **stream.kt** after attribute validation (_isValidXmlAttributeName()_ method call). As I see, any attribute which starts with "xml" prefix is considered invalid (is there a reason for this?).

**Comment by cy6erGn0m** [comment]
Am I right that the only usecase is to set `html`'s namespace?

**Comment by isitinschi** [comment]
According to [this](https://www.w3schools.com/xml/xml_namespaces.asp), any tag can have a namespace. But I am mostly interested in **html** tag.

**Comment by cy6erGn0m** [comment]
Currently setting attributes with namespace is not supported this is why it doesn't pass particular characters like colons and doesn't allow any attribute names starting with 'xml' (because these are reserved by the XML specification). 

Currently the only supported namespace-related feature is setting namespace at tag construction (that is required, for example, for SVG).

`namespace` property couldn't be modifiable because there is no way to amend it for an existing DOM element unless recreate the element and all the children. 

Also note that in spite of that any tag can have a namespace, assiging a namespace to a tag will make it completely different tag from browser's point of view. The `html` tag is an exception so I believe the quick workaround is to add optional `namespace` parameter to `html {}` function

**Comment by isitinschi** [comment]
Thank you!
